# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.10"
#  config.vm.network "private_network", type: "dhcp"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "2"
    vb.name = "redmine"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # system setting
    timedatectl set-timezone Asia/Tokyo
    setenforce 0
    sed -i -e 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
    # install packages
    yum -y groupinstall "Development Tools"
    yum -y install openssl-devel readline-devel zlib-devel curl-devel libyaml-devel libffi-devel
    yum -y install postgresql-server postgresql-devel
    yum -y install httpd httpd-devel
    yum -y install ImageMagick ImageMagick-devel ipa-pgothic-fonts
    # install ruby
    if [ ! -d ruby-2.4.1 ]; then
      curl -O https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.gz
      tar xf ruby-2.4.1.tar.gz && rm ruby-2.4.1.tar.gz
    fi
    cd ruby-2.4.1
    ./configure --disable-install-doc
    make
    make install
    /usr/local/bin/gem install bundler --no-rdoc --no-ri
    cd ..
    # install redmine
    svn co https://svn.redmine.org/redmine/branches/3.4-stable /var/lib/redmine <<<"p"
    cd /var/lib/redmine
    /usr/local/bin/bundle install --without development test --path vendor/bundle
    # install passenger
    /usr/local/bin/gem install passenger --no-rdoc --no-ri
    /usr/local/bin/passenger-install-apache2-module --auto --languages ruby
    # postgreSQL setting
    postgresql-setup initdb
    sed -i -E '/# Put your actual configuration here/a host    redmine         redmine         127.0.0.1/32            trust' /var/lib/pgsql/data/pg_hba.conf
    sed -i -E '/# Put your actual configuration here/a host    redmine         redmine         ::1/128                 trust' /var/lib/pgsql/data/pg_hba.conf
    systemctl start postgresql.service
    systemctl enable postgresql.service
    cd /var/lib/pgsql
    sudo -u postgres createuser redmine
    sudo -u postgres createdb -E UTF-8 -l ja_JP.UTF-8 -O redmine -T template0 redmine
    cd ~
    # setting redmine
    cat >/var/lib/redmine/config/database.yml <<EOF
production:
  adapter: postgresql
  database: redmine
  host: localhost
  username: redmine
  password: ""
  encoding: utf8
EOF
    cat >/var/lib/redmine/config/configuration.yml <<EOF
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "localhost"
      port: 25
      domain: "localdomain"
  rmagick_font_path: /usr/share/fonts/ipa-pgothic/ipagp.ttf
EOF
    cd /var/lib/redmine
    /usr/local/bin/bundle install --without development test --path vendor/bundle
    /usr/local/bin/bundle exec rake generate_secret_token
    RAILS_ENV=production /usr/local/bin/bundle exec rake db:migrate
    RAILS_ENV=production REDMINE_LANG=ja /usr/local/bin/bundle exec rake redmine:load_default_data
    # configure passenger
    cat >/etc/httpd/conf.d/redmine.conf <<EOF
# allow Redmine files
<Directory "/var/lib/redmine/public">
  Require all granted
</Directory>
EOF
    echo "# Basic setting for Passenger" >>/etc/httpd/conf.d/redmine.conf
    /usr/local/bin/passenger-install-apache2-module --snippet >>/etc/httpd/conf.d/redmine.conf
    cat >>/etc/httpd/conf.d/redmine.conf <<EOF
# tuning for passenger(option)
# show Phusion Passenger users guide(https://www.phusionpassenger.com/library/config/apache/reference/)
PassengerMaxPoolSize 20
PassengerMaxInstancesPerApp 4
PassengerPoolIdleTime 864000
PassengerStatThrottleRate 10

Header always unset "X-Powered-By"
Header always unset "X-Runtime"
EOF
    # configure for apache
    chown -R apache:apache /var/lib/redmine
    sed -i -e '/^DocumentRoot/c DocumentRoot "/var/lib/redmine/public"' /etc/httpd/conf/httpd.conf
    systemctl start httpd.service
    systemctl enable httpd.service
  SHELL
end
