# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.cache.scope = :box if Vagrant.has_plugin?("vagrant-cachier")
  (1..2).each do |i|
    config.vm.define "cassandra#{i}" do |node|
      node.vm.hostname = "cassandra#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{40+i}"
      config.vm.provider "virtualbox" do |vb|
        vb.name = node.vm.hostname
        vb.memory = "1048"
        vb.cpus = "1"
      end
      config.vm.provision "shell", name:"system setting",inline: <<-SHELL
        # system setting
        apt-get install locales
        sed -i -e "s/# ja_JP.*/ja_JP.UTF-8 UTF-8/" /etc/locale.gen
        dpkg-reconfigure -f noninteractive locales
        update-locale LANG=ja_JP.UTF-8
        timedatectl set-timezone Asia/Tokyo
      SHELL
      config.vm.provision "shell",name:"install packages", inline: <<-SHELL
        # install packages
        apt-get install -y openjdk-8-jdk-headless python-minimal python-pip
      SHELL
      config.vm.provision "shell",name:"install cassandra", inline: <<-SHELL
        # install cassandra
        echo "deb http://www.apache.org/dist/cassandra/debian 36x main" | sudo tee /etc/apt/sources.list.d/cassandra.sources.list
        curl -s https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
        apt-get update
        apt-get install -y cassandra
        pip install cassandra-driver
      SHELL
    end
  end
end
