# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
#  config.vm.network "private_network", ip: "192.168.56.41"
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "cassandranode1"
    node1.vm.network "private_network", ip: "192.168.56.41"
    config.vm.provider "virtualbox" do |vb|
      vb.name = node1.vm.hostname
      vb.memory = "1048"
      vb.cpus = "1"
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.hostname = "cassandranode2"
    node2.vm.network "private_network", ip: "192.168.56.42"
    config.vm.provider "virtualbox" do |vb|
      vb.name = node2.vm.hostname
      vb.memory = "1048"
      vb.cpus = "1"
    end
  end
#  config.vm.define "node3" do |node3|
#    node3.vm.hostname = "node3"
#    node3.vm.network "private_network", ip: "192.168.10.12"
#  end
#  config.vm.provision "shell", inline: <<-SHELL
#    # system setting
#    timedatectl set-timezone Asia/Tokyo
#    yum update -y
#  SHELL
#  config.vm.provision "shell", path: "create_user.sh"
#  config.vm.provision "shell", path: "create_dir.sh"
end
